### PR TITLE
This is a Travis CI GitHub integration test. Do Not Merge.

### PR DESCRIPTION
**Pull request by kellyselden**

### CODE REVIEW

**Comment by cvan** [comment]
@kellyselden Travis CI functionality looks okay to me. everything look fine to you?

**Comment by kellyselden** [comment]
@cvan The Travis CI hook is not turned on. I just rebased this branch, and it still isn't working. An admin of this project needs to add this repo to Travis CI in #222.

**Comment by cvan** [comment]
@toji ^

**Comment by jsantell** [comment]
Travis support now enabled, thanks all!

**Pull request closed without merging**
