### PR TITLE
rotate instructions interstitial emits event on show/hide

### LINKED ISSUE #93: a way for the rotate instructions interstitial to announce its show/hide-ing
e.g. `document.body.dispatchEvent(new CustomEvent('VRInstructionsShown'))`

### PR DESCRIPTION
**Pull request by gmarinov**
resolves #93

### CODE REVIEW

**Comment by borismus** [comment]
For consistency, this should be on window. Also, please document it in the readme.

**Comment by borismus** [comment]
Still not emitted on window object.

**Comment by borismus** [comment]
This might need more thought, since the WebVR implementation will also provide an interstitial. @toji, any plans to have one event for going into VR mode, and a separate event for showing that the interstitial disappeared?

**Comment by toji** [comment]
I'm curious what the use case is for these events. If the display `canPresent`, you should be able to assume that any interstitial is shown when you call `requestPresent` for the first time, and hidden when the promise returned by `requestPresent` resolves (and/or `vrdisplaypresentchange` fires.)

Beyond that, though the interstitial really should be treated as an opaque part of the UA. On desktop it's not necessary, but some UAs may introduce a permission prompt that needs to be clicked through before presentation starts. In that case, again, the signal for when presentation actually begins is the promise resolution and event.

**Comment by gmarinov** [comment]
@toji here are three reasons

 - when the content in the interstitial requires modification. not everybody likes a cardboard advert on that screen.
 - to address situations in CSS/layout/positioning that result in a need to switch elements behind the scenes, or more typically a need to hide/show elements that interfere with the instructions and/or/if the renderer reading the size of its container.
- in embed situations on e.g. iOS when "enter VR" breaks out of an iframe, navigating to a new URL, then the instructions are displayed automatically without any user action (in the context of the new page)

**Comment by borismus** [comment]
Native WebVR API isn't emitting these events either. Closing.

**Pull request closed without merging**
