### PR TITLE
Use content-box as box sizing method.

### PR DESCRIPTION
**Pull request by lennerd**
It's common practice to apply `box-sizing: border-box;` to elements via the `*` operator. This causes a bug when using the WebVR polyfill and the fullscreen Hack for iOS devices.

The polyfill applies some padding to overflow the content in every case causing a fullscreen without navigation and action bar. The `border-box` model adds this padding to the width and height of the canvas, causing the canvas to shift to the top left corner.

img_4775

Master: http://lennerd.taurus.uberspace.de/temp/webvr-polyfill-example/master.html
PR: http://lennerd.taurus.uberspace.de/temp/webvr-polyfill-example/pr.html

*I changed the body background to be red to see bug properly.*

This PRs simply adds `box-sizing: content-box` to the canvas when the CSS for the fullscreen view is applied.

Also see: https://github.com/googlevr/webvr-polyfill/pull/131#issuecomment-279972199

### CODE REVIEW

**Comment by lennerd** [comment]
I signed it!

**Comment by borismus** [comment]
Sorry, your PR has a bunch of DPDB changes as well. Please revert them. Also, have you tested the box-sizing changes on Android, iOS, desktop, vive, etc?

**Comment by lennerd** [comment]
DPDB? Sorry, not sure, what you mean. Probably the stuff from the build file? Thought we need to add also a ready build file. Of course I can revert this.

> Also, have you tested the box-sizing changes on Android, iOS, desktop, vive, etc?

I tested this PR only on iOS. Not sure how other devices will differ though. As `content-box` is also the initial/default value for `box-sizing`, this PR just makes sure that these default behaviour is applied even when a global `box-sizing` is set, no?

**Comment by borismus** [comment]
Could you please test box sizing on desktop and android? Thanks

**Comment by cvan** [comment]
per @borismus' comment: are you positive this doesn't cause regressions on any browser/platform combinations?

**Comment by lennerd** [comment]
I don't have an Android phone at hand at the moment, but I already tested this on a Desktop device though.

But again: my changes simply restore the default `content-box` for `box-sizing` a browser is using anyway if no own `box-sizing` is defined via a concrete or an asterik selector. I don't see why this should break any working setup. Am I missing something?

**Comment by lennerd** [comment]
And please explain to me DPDB. Not able to find anything on the internet explaining it.

**Comment by toji** [comment]
Fixed by #212

**Pull request closed without merging**
