### PR TITLE
Removes event firing when changing the layers during presentation

### PR DESCRIPTION
**Pull request by AVGP**
If I understood #154 correctly, the polyfill should no longer fire the `vrdisplaypresentchange` event, but still allow changes to the layers during presentation.

### CODE REVIEW

**Comment by AVGP** [comment]
Great... so I'm using one email as my public Github email and when I try to sign the CLA it keeps insisting that I have signed this CLA but shows my personal GMail address.

My public email is setup as an alternate address for my GMail account, yet I can't change the email for the CLA. What do I do? :(

**Comment by AVGP** [comment]
Well, nevermind then :-)

**Comment by AVGP** [comment]
I signed it!

Am 20.10.2016 8:07 nachm. schrieb "googlebot" <notifications@github.com>:

**Comment by brianchirls** [comment]
Looks okay to me.

**Pull request merged**
