### PR TITLE
Save and restore vertex attributes in CardboardDistorter

### PR DESCRIPTION
**Pull request by daredevildave**
Fixes bugs in PlayCanvas where we have cached vertex attribute state. FAO @toji ?

### CODE REVIEW

**Comment by toji** [comment]
Logic looks good, but I've found that querying attributes like this has been one of the biggest sources of slowdown in previous iterations of the polyfill. The preferred method (ugly though it may be) would be to swap out the relevant calls on the context with ones that cache the incoming values before sending them down to the real function. See `CardboardDistorter.prototype.patch`/`CardboardDistorter.prototype.unpatch` for multiple examples.

**Comment by borismus** [comment]
@daredevildave Any updates here?

**Comment by daredevildave** [comment]
Sorry, haven't had a chance to update the code to the more performant version. However, we're using it with this change merged currently on PlayCanvas. I'll try and update this week.

**Comment by borismus** [comment]
Ping!

**Comment by borismus** [comment]
Closing for inactivity.

**Pull request closed without merging**
