### PR TITLE
Android WebView fullscreen bug fix #114

### LINKED ISSUE #114: Allow to launch the vr mode without being in fullscreen
When the webvr-polyfill is used in the android web-view inside an application in can't launch the vr mode because it won't go in fullscreen

### PR DESCRIPTION
**Pull request by serghov**
Allow going into VR mode without being in fullscreen when inside android WebView (similar to IOS webview)

### CODE REVIEW

**Comment by serghov** [comment]
I signed it!

**Comment by grigorkh** [comment]
I signed it!

**Comment by serghov** [comment]
I signed it!

**Comment by grigorkh** [comment]
It's ok, I confirm.

**Comment by borismus** [comment]
I don't think WebView support should be in scope at the moment.

**Comment by andymartinwork** [comment]
Hey, why has this PR been closed?

I'm building a web browser for WebVR for both Cardboard and Android and denying this PR breaks it for pretty much all new VR websites (since this polyfill is now part of a-frame).

Please strongly reconsider this. I don't understand why you *wouldn't* want to support the webview.

**Comment by dmarcos** [comment]
@borismus I know it's a PITA to add more platforms to support but Is there any chance to reconsider this PR? Is there anything we can do to improve it? We have a-frame have users building experiences on top of webviews and this is the only thing preventing them to do what they need. Thanks for all of your work

**Comment by mn-martin** [comment]
Please reconsider this. +1

**Comment by cvan** [comment]
@borismus @toji Kindly bumping to get this PR reconsidered? See issues #114 and aframevr/aframe#1231.

**Comment by brianchirls** [comment]
Can someone clarify - is a PWA installed to home screen in a web view?

**Comment by toji** [comment]
I don't see the harm in trying to support this use case better.

**Comment by jsantell** [comment]
Thank you for the original patch! The streamlined version of the patch was merged into [aframe's fork](https://github.com/aframevr/webvr-polyfill), and subsequently merged here via e55d7172b9665ef5316434095c783706a3b59758

**Pull request closed without merging**
